name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # The branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Adjust the version if necessary

      - name: Install dependencies
        run: npm install  # Adjust if using yarn or another package manager

      - name: Build the project
        run: npm run build  # Adjust the build command if needed

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Adjust to your build directory
